### ISSUE TITLE
Throw error if any sort of redirect_uri is provided in client_credentials grant

### ISSUE THREAD

**Issue by dmitrizagidulin** [digitalbazaar/oauth2-token-endpoint-handler#8]
OAuth 2.0 spec makes `redirect_uri` an optional parameter.
However, to prevent any sort of CSRF attacks or confusion, throw an error if a `redirect_uri` param is provided for a `grant_type` of `client_credentials` (which does not use that parameter).

**Comment by JSAssassin** [comment]
Closing, this has been implemented here https://github.com/digitalbazaar/oauth2-token-endpoint-handler/pull/10
